name: test-release

on: workflow_dispatch

jobs:
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      # list bin folder
      - name: list bin folder
        run: ls
        working-directory: target/release
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp target/release/hash_zome target/release/hash_zome_linux
          gh release upload "manual-release" "target/release/hash_zome_linux" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp target/release/hash_zome target/release/hash_zome_mac
          gh release upload "manual-release" "target/release/hash_zome_mac" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "target/release/hash_zome.exe" --clobber