name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and upload hash_zome binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: hash_zome
          tar: all
          zip: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and upload unpack_webhapp binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: unpack_webhapp
          tar: all
          zip: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
